server:
  port: 7000
  servlet:
    context-path: /homepage-user

# spring相关数据源配置
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: eureka-client-homepage-user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://39.96.21.162:3306/imooc_homepage_sc?characterEncoding=utf8&useSSL=false
    username: lutong
    password: Lutong~918
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2


# 将服务注册到localhost这个节点的Eureka上，如果是集群就  url,url,url,....
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

feign:
  hystrix:
    enabled: true
